version: '3'

services:

  postgres-shop:
    container_name: postgres-shop
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user-shop
      PGDATA: /data/PostTestApi
    volumes:
      - postgres:/data/postgres
    ports:
      - "5455:5432"
    restart: unless-stopped
    networks:
      - app
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - postgres-shop
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-shop:5432/user-shop
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - app

volumes:
  postgres:
    external: true
networks:
  app:
    driver: bridge






