server:
  port: 8088

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5455/user-shop
    username: user
    password: user

  jpa:
    show-sql: true

jwt:
  secret: my-super-secret-key
  expiration: 360000

