name: Java CI with Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Create Docker volume
        run: docker volume create --name=postgres

      - name: Start Docker containers
        run: |
          docker-compose up -d postgres-shop
          docker-compose up -d spring-app
          docker-compose ps
          sleep 30
          docker-compose logs spring-app

      - name: Build Docker images
        run: docker-compose build

