name: Java CI with Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - "5432:5432"
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: user
          POSTGRES_DB: user-shop
          PGDATA: /data/PostTestApi

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build Spring Boot application
      run: |
        docker-compose build
        docker-compose up -d postgres-shop
        docker-compose up -d spring-app
        docker-compose ps
        sleep 30
        docker-compose logs spring-app

    - name: Wait for application to be ready
      run: dockerize -wait tcp://localhost:8088 -timeout 1m

    - name: Run tests (if applicable)
      run: |
        # Add commands to run your tests here

    - name: Publish to GitHub Packages (optional)
      run: mvn deploy -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
